// src/frontend/app/components/RoundTable.tsx
//
// ARCH-ROUND-TABLE-001 (2026-07-20): renders the "## The Round Table" block
// from .pmcro/SESSION-BRIEF.md. The Colony's Round Table is regenerated by
// /orchestrator:brief-session each cycle and lives in that file (relocated
// from repo root on 2026-07-19 per .pmcro/README.md). This component fetches
// the raw markdown from the project root and parses only the Round Table
// section -- nothing is hardcoded, so a refreshed brief shows up on reload.
// Parsing strategy: split on the "## The Round Table" heading, take
// everything up to the next "## " heading, then turn each "**role:** " line
// into a labeled turn. Lines that are plain prose (e.g. the Unified
// Repository note) are included as a trailing note.
"use client";

import { useEffect, useRef, useState } from "react";

type Turn = {
  role: string;
  text: string;
};

async function loadRoundTable(): Promise<{ turns: Turn[]; note?: string }> {
  const res = await fetch("/SESSION-BRIEF.md", { cache: "no-store" });
  if (!res.ok) return { turns: [] };
  const md = await res.text();
  const start = md.indexOf("## The Round Table");
  if (start === -1) return { turns: [] };
  const after = md.slice(start + "## The Round Table".length);
  const end = after.indexOf("\n## ");
  const block = (end === -1 ? after : after.slice(0, end)).trim();

  const turns: Turn[] = [];
  let note: string | undefined;
  let current: Turn | null = null;

  for (const raw of block.split("\n")) {
    const line = raw.trim();
    if (!line) continue;
    const m = line.match(/^\*\*(.+?):\*\*\s*(.*)$/);
    if (m) {
      current = { role: m[1], text: m[2] };
      turns.push(current);
    } else if (line.startsWith("**") && line.endsWith("**")) {
      note = (note ? note + " " : "") + line.replace(/\*\*/g, "");
    } else if (current) {
      current.text += " " + line.replace(/^"/, "").replace(/"$/, "");
    } else {
      note = (note ? note + " " : "") + line;
    }
  }
  return { turns, note: note?.trim() || undefined };
}

// ARCH-NEURAL-ACTION-001 (2026-07-20): how long each turn stays highlighted
// during an LLM-driven playBriefing() playback, in ms.
const PLAYBACK_STEP_MS = 2200;

export default function RoundTable({ playTrigger }: { playTrigger?: number } = {}) {
  const [turns, setTurns] = useState<Turn[]>([]);
  const [note, setNote] = useState<string | undefined>(undefined);
  const [loaded, setLoaded] = useState(false);
  const [activeIndex, setActiveIndex] = useState<number | null>(null);
  // ARCH-ROUND-TABLE-CLAMP-001 (2026-07-20): tracks which turns the user
  // has manually expanded past the default 3-line clamp (see globals.css
  // .round-table-text[data-clamped]). Keyed by index so re-loading a
  // refreshed brief resets everyone back to collapsed.
  const [expanded, setExpanded] = useState<Record<number, boolean>>({});
  const sectionRef = useRef<HTMLElement | null>(null);
  const playRunId = useRef(0);

  // A turn is worth clamping/toggling only once it's long enough to
  // actually overflow 3 lines at this column width -- short one-line turns
  // (e.g. "no cycles run yet.") never get a toggle button.
  const CLAMP_THRESHOLD = 220;

  useEffect(() => {
    loadRoundTable().then((r) => {
      setTurns(r.turns);
      setNote(r.note);
      setLoaded(true);
    });
  }, []);

  // ARCH-NEURAL-ACTION-001: real (not simulated-elsewhere) narrative
  // playback -- steps activeIndex through the parsed turns on a fixed
  // interval, scrolling the section into view first. `playRunId` invalidates
  // any in-flight timeout chain from a prior trigger so two rapid
  // playBriefing() calls can't race and leave two chains running.
  useEffect(() => {
    if (!playTrigger || turns.length === 0) return;
    const runId = ++playRunId.current;
    sectionRef.current?.scrollIntoView({ behavior: "smooth", block: "start" });

    let i = 0;
    setActiveIndex(0);
    const timer = setInterval(() => {
      if (playRunId.current !== runId) {
        clearInterval(timer);
        return;
      }
      i += 1;
      if (i >= turns.length) {
        clearInterval(timer);
        setActiveIndex(null);
        return;
      }
      setActiveIndex(i);
    }, PLAYBACK_STEP_MS);

    return () => clearInterval(timer);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [playTrigger]);

  return (
    <section id="round-table" className="colony-section" ref={sectionRef}>
      <h2 className="colony-section-title">Round Table</h2>
      {!loaded ? (
        <p className="colony-hint">Loading the Colony's Round Table from SESSION-BRIEF.md…</p>
      ) : turns.length === 0 ? (
        <p className="colony-hint">
          No Round Table section found in .pmcro/SESSION-BRIEF.md — run{" "}
          <code>/orchestrator:brief-session</code> to populate it.
        </p>
      ) : (
        <div className="round-table">
          {turns.map((t, i) => {
            const longEnough = t.text.length > CLAMP_THRESHOLD;
            // During playBriefing() playback, the turn currently being
            // narrated (i === activeIndex) always shows in full -- clamping
            // the exact turn the highlight is pointing at would defeat the
            // point of the playback.
            const isExpanded = expanded[i] === true || i === activeIndex;
            return (
              <div
                className="round-table-turn"
                data-active={i === activeIndex}
                key={`${t.role}-${i}`}
              >
                <span className="round-table-role">{t.role}</span>
                <div>
                  <p
                    className="round-table-text"
                    data-clamped={longEnough && !isExpanded ? "true" : "false"}
                  >
                    {t.text}
                  </p>
                  {longEnough && (
                    <button
                      type="button"
                      className="round-table-toggle"
                      onClick={() => setExpanded((prev) => ({ ...prev, [i]: !isExpanded }))}
                    >
                      {isExpanded ? "Show less" : "Show more"}
                    </button>
                  )}
                </div>
              </div>
            );
          })}
          {note && <p className="round-table-note">{note}</p>}
        </div>
      )}
    </section>
  );
}